"""IX-BlackFox-Cognition public API.

IX-BlackFox-Cognition is a source-available governed cognition substrate for
evidence-bound AI-assisted engineering workflows.

The current public API exports stable project metadata, dependency-light core
types, authority models, authority firewall logic, mission models, deterministic
mission intake, epistemic claim-ledger models, evidence-contract models,
belief-graph models, immutable belief-graph logic, proof-carrying plan graph
models, conservative plan validation, cognitive work package models,
model-role tribunal models, conservative model separation routing, memory
immune-system data models, memory quarantine/promotion logic, cognitive sentinel
checks, and BlackFox-compatible handoff protocol models. Higher-level
self-improvement APIs will be exported only after their modules exist and are
covered by tests.
"""

from ix_blackfox_cognition.authority import (
    AuthorityBoundary,
    AuthorityDecisionRecord,
    AuthorityLevel,
    AuthorityRequest,
    AuthoritySnapshot,
    CognitionPermission,
    ForbiddenAction,
    HumanAuthorityRequirement,
)
from ix_blackfox_cognition.authority_firewall import (
    AuthorityFirewall,
    AuthorityFirewallPolicy,
    evaluate_authority_request,
)
from ix_blackfox_cognition.belief_graph import (
    BeliefContradiction,
    BeliefEdge,
    BeliefGraph,
    BeliefKind,
    BeliefNode,
    BeliefRelationKind,
    BeliefStatus,
    StaleBeliefMarker,
)
from ix_blackfox_cognition.belief_graph_logic import (
    BeliefDecisionKind,
    BeliefGraphDecision,
    BeliefGraphEngine,
    BeliefGraphOperationResult,
    promote_belief,
)
from ix_blackfox_cognition.core import (
    ActorKind,
    AuthorityError,
    ClaimState,
    CognitionError,
    CognitionInvariantError,
    CognitionMemoryError,
    DecisionOutcome,
    EvidenceError,
    EvidenceState,
    FailureMode,
    FailureRecord,
    MemoryState,
    PolicyError,
    RiskLevel,
    SelfImprovementError,
    WorkState,
    fail_closed,
    require_invariant,
)
from ix_blackfox_cognition.epistemics import (
    ClaimKind,
    ClaimLedger,
    ClaimRecord,
    ClaimSource,
    ClaimStateTransition,
    ConfidenceBasis,
    ConfidenceSignal,
)
from ix_blackfox_cognition.evidence import (
    EvidenceContract,
    EvidenceKind,
    EvidenceReference,
    EvidenceRequirement,
    EvidenceSource,
    EvidenceStrength,
    FalsificationCondition,
    ProofObligation,
)
from ix_blackfox_cognition.handoff import (
    BlackFoxActionCandidate,
    BlackFoxActionKind,
    BlackFoxExecutionRequest,
    BlackFoxHandoffDecision,
    BlackFoxHandoffEnvelope,
    BlackFoxHandoffGate,
    BlackFoxHandoffResult,
    HandoffReadiness,
    RequiredTest,
    RollbackPlan,
    evaluate_blackfox_handoff,
)
from ix_blackfox_cognition.memory import (
    MemoryConflict,
    MemoryConflictKind,
    MemoryQuarantineRecord,
    MemoryRecord,
    MemoryRecordKind,
    MemorySource,
    MemoryStore,
    MemoryUpdateKind,
    MemoryUpdateProposal,
)
from ix_blackfox_cognition.memory_logic import (
    MemoryDecision,
    MemoryDecisionKind,
    MemoryImmunePolicy,
    MemoryImmuneSystem,
    MemoryOperationResult,
    promote_memory_proposal,
    submit_memory_proposal,
)
from ix_blackfox_cognition.metadata import (
    CORE_DOCTRINE,
    FOUNDATIONAL_LAW,
    LICENSE_NAME,
    PACKAGE_NAME,
    PROJECT_NAME,
    PROHIBITED_CLAIMS,
    PUBLIC_DESCRIPTION,
    RESEARCH_STATUS,
    VERSION,
    PackageIdentity,
    get_package_identity,
)
from ix_blackfox_cognition.mission import (
    AcceptanceCriterion,
    HumanGoal,
    MissionAssumption,
    MissionAssumptionState,
    MissionConstraint,
    MissionConstraintKind,
    MissionEnvelope,
    MissionReviewTrigger,
    MissionRisk,
    ReviewCheckpoint,
    RollbackNeed,
)
from ix_blackfox_cognition.mission_intake import (
    DEFAULT_FORBIDDEN_ACTIONS,
    MissionIntakeDefaults,
    MissionIntakeEngine,
    MissionIntakeRequest,
    MissionIntakeResult,
    structure_mission,
)
from ix_blackfox_cognition.plan_validation import (
    PlanGraphValidator,
    PlanValidationFinding,
    PlanValidationPolicy,
    PlanValidationResult,
    PlanValidationSeverity,
    validate_plan_graph,
)
from ix_blackfox_cognition.planning import (
    PlanDependencyKind,
    PlanEdge,
    PlanGraph,
    PlanNode,
    PlanNodeKind,
    PlanReviewRequirement,
    PlanReviewTrigger,
    PlanRollbackCondition,
)
from ix_blackfox_cognition.routing import (
    ModelAssignment,
    ModelCapability,
    ModelIdentity,
    ModelProviderKind,
    ModelRoleKind,
    ModelRoleSpec,
    ModelRouteDecision,
    ModelRouteRequest,
    ModelTribunal,
    RoutePurpose,
)
from ix_blackfox_cognition.routing_logic import (
    ModelRouter,
    RouteSeparationPolicy,
    route_model_request,
)
from ix_blackfox_cognition.sentinel import (
    CognitiveArtifactSnapshot,
    CognitiveIssueKind,
    CognitiveIssueSeverity,
    CognitiveSentinel,
    CognitiveSentinelIssue,
    CognitiveSentinelPolicy,
    CognitiveSentinelReport,
    inspect_cognition,
)
from ix_blackfox_cognition.work_packages import (
    CognitiveWorkPackage,
    WorkPackageBatch,
    WorkPackageDependency,
    WorkPackageKind,
    WorkPackageOutputKind,
    WorkPackageReviewGate,
)

__version__ = VERSION

__all__ = [
    "DEFAULT_FORBIDDEN_ACTIONS",
    "AcceptanceCriterion",
    "ActorKind",
    "AuthorityBoundary",
    "AuthorityDecisionRecord",
    "AuthorityError",
    "AuthorityFirewall",
    "AuthorityFirewallPolicy",
    "AuthorityLevel",
    "AuthorityRequest",
    "AuthoritySnapshot",
    "BeliefContradiction",
    "BeliefDecisionKind",
    "BeliefEdge",
    "BeliefGraph",
    "BeliefGraphDecision",
    "BeliefGraphEngine",
    "BeliefGraphOperationResult",
    "BeliefKind",
    "BeliefNode",
    "BeliefRelationKind",
    "BeliefStatus",
    "BlackFoxActionCandidate",
    "BlackFoxActionKind",
    "BlackFoxExecutionRequest",
    "BlackFoxHandoffDecision",
    "BlackFoxHandoffEnvelope",
    "BlackFoxHandoffGate",
    "BlackFoxHandoffResult",
    "CORE_DOCTRINE",
    "ClaimKind",
    "ClaimLedger",
    "ClaimRecord",
    "ClaimSource",
    "ClaimState",
    "ClaimStateTransition",
    "CognitionError",
    "CognitionInvariantError",
    "CognitionMemoryError",
    "CognitionPermission",
    "CognitiveArtifactSnapshot",
    "CognitiveIssueKind",
    "CognitiveIssueSeverity",
    "CognitiveSentinel",
    "CognitiveSentinelIssue",
    "CognitiveSentinelPolicy",
    "CognitiveSentinelReport",
    "CognitiveWorkPackage",
    "ConfidenceBasis",
    "ConfidenceSignal",
    "DecisionOutcome",
    "EvidenceContract",
    "EvidenceError",
    "EvidenceKind",
    "EvidenceReference",
    "EvidenceRequirement",
    "EvidenceSource",
    "EvidenceState",
    "EvidenceStrength",
    "FOUNDATIONAL_LAW",
    "FailureMode",
    "FailureRecord",
    "FalsificationCondition",
    "ForbiddenAction",
    "HandoffReadiness",
    "HumanAuthorityRequirement",
    "HumanGoal",
    "LICENSE_NAME",
    "MemoryConflict",
    "MemoryConflictKind",
    "MemoryDecision",
    "MemoryDecisionKind",
    "MemoryImmunePolicy",
    "MemoryImmuneSystem",
    "MemoryOperationResult",
    "MemoryQuarantineRecord",
    "MemoryRecord",
    "MemoryRecordKind",
    "MemorySource",
    "MemoryState",
    "MemoryStore",
    "MemoryUpdateKind",
    "MemoryUpdateProposal",
    "MissionAssumption",
    "MissionAssumptionState",
    "MissionConstraint",
    "MissionConstraintKind",
    "MissionEnvelope",
    "MissionIntakeDefaults",
    "MissionIntakeEngine",
    "MissionIntakeRequest",
    "MissionIntakeResult",
    "MissionReviewTrigger",
    "MissionRisk",
    "ModelAssignment",
    "ModelCapability",
    "ModelIdentity",
    "ModelProviderKind",
    "ModelRoleKind",
    "ModelRoleSpec",
    "ModelRouteDecision",
    "ModelRouteRequest",
    "ModelRouter",
    "ModelTribunal",
    "PACKAGE_NAME",
    "PROJECT_NAME",
    "PROHIBITED_CLAIMS",
    "PUBLIC_DESCRIPTION",
    "PackageIdentity",
    "PlanDependencyKind",
    "PlanEdge",
    "PlanGraph",
    "PlanGraphValidator",
    "PlanNode",
    "PlanNodeKind",
    "PlanReviewRequirement",
    "PlanReviewTrigger",
    "PlanRollbackCondition",
    "PlanValidationFinding",
    "PlanValidationPolicy",
    "PlanValidationResult",
    "PlanValidationSeverity",
    "PolicyError",
    "ProofObligation",
    "RESEARCH_STATUS",
    "RequiredTest",
    "ReviewCheckpoint",
    "RiskLevel",
    "RollbackNeed",
    "RollbackPlan",
    "RoutePurpose",
    "RouteSeparationPolicy",
    "SelfImprovementError",
    "StaleBeliefMarker",
    "VERSION",
    "WorkPackageBatch",
    "WorkPackageDependency",
    "WorkPackageKind",
    "WorkPackageOutputKind",
    "WorkPackageReviewGate",
    "WorkState",
    "evaluate_authority_request",
    "evaluate_blackfox_handoff",
    "fail_closed",
    "get_package_identity",
    "inspect_cognition",
    "promote_belief",
    "promote_memory_proposal",
    "require_invariant",
    "route_model_request",
    "structure_mission",
    "submit_memory_proposal",
    "validate_plan_graph",
]
