"""IX-BlackFox-Cognition public API.

IX-BlackFox-Cognition is a source-available governed cognition substrate for
evidence-bound AI-assisted engineering workflows.

The current public API exports stable project metadata, dependency-light core
types, authority models, authority firewall logic, mission models, deterministic
mission intake, epistemic claim-ledger models, evidence-contract models,
belief-graph models, and immutable belief-graph logic. Higher-level planning,
memory, routing, sentinel, and handoff APIs will be exported only after their
modules exist and are covered by tests.
"""

from ix_blackfox_cognition.authority import (
    AuthorityBoundary,
    AuthorityDecisionRecord,
    AuthorityLevel,
    AuthorityRequest,
    AuthoritySnapshot,
    CognitionPermission,
    ForbiddenAction,
    HumanAuthorityRequirement,
)
from ix_blackfox_cognition.authority_firewall import (
    AuthorityFirewall,
    AuthorityFirewallPolicy,
    evaluate_authority_request,
)
from ix_blackfox_cognition.belief_graph import (
    BeliefContradiction,
    BeliefEdge,
    BeliefGraph,
    BeliefKind,
    BeliefNode,
    BeliefRelationKind,
    BeliefStatus,
    StaleBeliefMarker,
)
from ix_blackfox_cognition.belief_graph_logic import (
    BeliefDecisionKind,
    BeliefGraphDecision,
    BeliefGraphEngine,
    BeliefGraphOperationResult,
    promote_belief,
)
from ix_blackfox_cognition.core import (
    ActorKind,
    AuthorityError,
    ClaimState,
    CognitionError,
    CognitionInvariantError,
    CognitionMemoryError,
    DecisionOutcome,
    EvidenceError,
    EvidenceState,
    FailureMode,
    FailureRecord,
    MemoryState,
    PolicyError,
    RiskLevel,
    SelfImprovementError,
    WorkState,
    fail_closed,
    require_invariant,
)
from ix_blackfox_cognition.epistemics import (
    ClaimKind,
    ClaimLedger,
    ClaimRecord,
    ClaimSource,
    ClaimStateTransition,
    ConfidenceBasis,
    ConfidenceSignal,
)
from ix_blackfox_cognition.evidence import (
    EvidenceContract,
    EvidenceKind,
    EvidenceReference,
    EvidenceRequirement,
    EvidenceSource,
    EvidenceStrength,
    FalsificationCondition,
    ProofObligation,
)
from ix_blackfox_cognition.metadata import (
    CORE_DOCTRINE,
    FOUNDATIONAL_LAW,
    LICENSE_NAME,
    PACKAGE_NAME,
    PROJECT_NAME,
    PROHIBITED_CLAIMS,
    PUBLIC_DESCRIPTION,
    RESEARCH_STATUS,
    VERSION,
    PackageIdentity,
    get_package_identity,
)
from ix_blackfox_cognition.mission import (
    AcceptanceCriterion,
    HumanGoal,
    MissionAssumption,
    MissionAssumptionState,
    MissionConstraint,
    MissionConstraintKind,
    MissionEnvelope,
    MissionReviewTrigger,
    MissionRisk,
    ReviewCheckpoint,
    RollbackNeed,
)
from ix_blackfox_cognition.mission_intake import (
    DEFAULT_FORBIDDEN_ACTIONS,
    MissionIntakeDefaults,
    MissionIntakeEngine,
    MissionIntakeRequest,
    MissionIntakeResult,
    structure_mission,
)

__version__ = VERSION

__all__ = [
    "DEFAULT_FORBIDDEN_ACTIONS",
    "AcceptanceCriterion",
    "ActorKind",
    "AuthorityBoundary",
    "AuthorityDecisionRecord",
    "AuthorityError",
    "AuthorityFirewall",
    "AuthorityFirewallPolicy",
    "AuthorityLevel",
    "AuthorityRequest",
    "AuthoritySnapshot",
    "BeliefContradiction",
    "BeliefDecisionKind",
    "BeliefEdge",
    "BeliefGraph",
    "BeliefGraphDecision",
    "BeliefGraphEngine",
    "BeliefGraphOperationResult",
    "BeliefKind",
    "BeliefNode",
    "BeliefRelationKind",
    "BeliefStatus",
    "CORE_DOCTRINE",
    "ClaimKind",
    "ClaimLedger",
    "ClaimRecord",
    "ClaimSource",
    "ClaimState",
    "ClaimStateTransition",
    "CognitionError",
    "CognitionInvariantError",
    "CognitionMemoryError",
    "CognitionPermission",
    "ConfidenceBasis",
    "ConfidenceSignal",
    "DecisionOutcome",
    "EvidenceContract",
    "EvidenceError",
    "EvidenceKind",
    "EvidenceReference",
    "EvidenceRequirement",
    "EvidenceSource",
    "EvidenceState",
    "EvidenceStrength",
    "FOUNDATIONAL_LAW",
    "FailureMode",
    "FailureRecord",
    "FalsificationCondition",
    "ForbiddenAction",
    "HumanAuthorityRequirement",
    "HumanGoal",
    "LICENSE_NAME",
    "MemoryState",
    "MissionAssumption",
    "MissionAssumptionState",
    "MissionConstraint",
    "MissionConstraintKind",
    "MissionEnvelope",
    "MissionIntakeDefaults",
    "MissionIntakeEngine",
    "MissionIntakeRequest",
    "MissionIntakeResult",
    "MissionReviewTrigger",
    "MissionRisk",
    "PACKAGE_NAME",
    "PROJECT_NAME",
    "PROHIBITED_CLAIMS",
    "PUBLIC_DESCRIPTION",
    "PackageIdentity",
    "PolicyError",
    "ProofObligation",
    "RESEARCH_STATUS",
    "ReviewCheckpoint",
    "RiskLevel",
    "RollbackNeed",
    "SelfImprovementError",
    "StaleBeliefMarker",
    "VERSION",
    "WorkState",
    "evaluate_authority_request",
    "fail_closed",
    "get_package_identity",
    "promote_belief",
    "require_invariant",
    "structure_mission",
]
